services:
  flood:
    image: jesec/flood
    user: ${UID}:${GID}
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - ${CONF_DIR}:/config
      - ${DATA_DIR}:/data
    ports:
      - 0.0.0.0:3001:3001

  rtorrent:
    image: jesec/rtorrent
    user: ${UID}:${GID}
    restart: unless-stopped
    command: -o network.port_range.set=6881-6881,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - ${CONF_DIR}:/config
      - ${DATA_DIR}:/data
    ports:
      - 0.0.0.0:6881:6881
